### PR TITLE
fix error when calling signout method with revoketokens set to true

### PR DESCRIPTION
**Pull request by xabierarima**
This branch fixes this issue:  https://github.com/wi3land/ionic-appauth/issues/220

Calling the signOut method with revokeTokens set to true fails because revokeTokens deletes the token from the storage and then the signOut method tries to delete the same token again.  My fix is to check that the token exists before deleting it.

I have also made a change to performEndSessionRequest. I don't check if _tokenSubject.value is undefined because if revokeTokens has been called before it will be undefined but we still want to call end session endpoint.

### CODE REVIEW

**Review by mraible — APPROVED** [review]

**Comment by mraible** [comment]
Thank you for your contribution, @xabierarima!

**Comment by xabierarima** [comment]
Hi @mraible,

Could you please create a new release that includes the changes from this PR?

**Comment by mraible** [comment]
@xabierarima I don't have the ability to do a release. Only @wi3land can do a release.

**Comment by wi3land** [comment]
@mraible I have you access to do releases last year via a GitHub action, you just need to create a new release and publish it.

**Comment by mraible** [comment]
@wi3land I'm sorry, that slipped my mind. I'll try to do a release now.

FWIW, I was [laid off from Okta](https://raibledesigns.com/rd/entry/funemployment_2024) in February, so my interest in this space could change depending on what I do next. However, we still use this library in [Ionic for JHipster](https://github.com/jhipster/generator-jhipster-ionic) and I'm interested in maintaining that functionality.

**Comment by mraible** [comment]
v2.1.0 has been published. https://github.com/wi3land/ionic-appauth/releases/tag/v2.1.0

**Pull request merged**
