### PR TITLE
Add Capacitor 4 support

### PR DESCRIPTION
**Pull request by mraible**
Fix https://github.com/wi3land/ionic-appauth/issues/128. 

Depends on https://github.com/martinkasa/capacitor-secure-storage-plugin/pull/59.

In the meantime, you can clone the following repo in a directory alongside this repo and build it first.

```
git clone git@github.com:martinkasa/capacitor-secure-storage-plugin.git
cd capacitor-secure-storage-plugin
npm i
npm run build
npm pack
```

Currently, I see the following issue on iOS when I run `npx cap open ios`. I'm not sure how to fix. 

```
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "Preferences" plugin is not implemented on ios
CapacitorException@capacitor://localhost/vendor.js:764:10
createPluginMethod@capacitor://localhost/vendor.js:886:37
@capacitor://localhost/vendor.js:895:40
onInvoke@capacitor://localhost/vendor.js:98549:31
@capacitor://localhost/polyfills.js:296:43
@capacitor://localhost/polyfills.js:1716:31
onInvokeTask@capacitor://localhost/vendor.js:98537:35
@capacitor://localhost/polyfills.js:353:49
drainMicroTaskQueue@capacitor://localhost/polyfills.js:823:32
promiseReactionJob@[native code]
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: "Browser" plugin is not implemented on ios
CapacitorException@capacitor://localhost/vendor.js:764:10
createPluginMethod@capacitor://localhost/vendor.js:886:37
@capacitor://localhost/vendor.js:895:40
onInvoke@capacitor://localhost/vendor.js:98549:31
@capacitor://localhost/polyfills.js:296:43
@capacitor://localhost/polyfills.js:1716:31
onInvokeTask@capacitor://localhost/vendor.js:98537:35
@capacitor://localhost/polyfills.js:353:49
drainMicroTaskQueue@capacitor://localhost/polyfills.js:823:32
promiseReactionJob@[native code]
```

### CODE REVIEW

**Comment by mraible** [comment]
I was able to fix these issues by running the following in my test app:

```
npm i @capacitor/browser@4.0.1 @capacitor/preferences@4.0.1
npx cap sync
```

**Comment by mraible** [comment]
@wi3land Are you able to test the demos with an identity server? I assume you set something up locally to test things in the past?

**Comment by de-dan** [comment]
Hey @mraible, could you also please run `npm update` to get rid of vulnerabilities?

**Comment by mraible** [comment]
I was able to get most of the demos working, except for Angular + Cordova.

**Pull request merged**
